#!/usr/bin/env bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Use scp to transfer the file with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~

# Check if the transfer was successful
if [ "$?" -eq 0 ]; then
    echo "File successfully transferred to ${$3}@${$2}:~/"
else
    echo "File transfer failed!"
fi
