#!/usr/bin/env bash
# Check if the number of arguments is less than 4

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Use scp to transfer the file with strict host key checking disabled
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "${USERNAME}@${SERVER_IP}:~/"

# Check if the transfer was successful
if [ "$?" -eq 0 ]; then
    echo "File successfully transferred to ${USERNAME}@${SERVER_IP}:~/"
else
    echo "File transfer failed!"
    exit 1
fi
