#!/usr/bin/env bash
# This script configures a new Ubuntu machine by installing Nginx
# ensuring it listens on port 80
# and serves a page with a "Hello World" string.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y
echo -e "\nSetting up some minor stuff.\n"
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i "50i\	add_header X-Served-By $hostname"
sudo service nginx restart
echo -e "\nCompleted.\n"o

