#!/usr/bin/env bash
# Script to configure a new Ubuntu machine
# with Nginx to serve a "Hello World" page
# and set up a redirection and custom header

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service and allowing on firewall
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating a new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up a redirection
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Setting up a custom header
sudo sed -i "50i\	add_header X-Served-By $hostname"

# restarting nginx service
sudo service nginx restart

echo -e "\nCompleted.\n"
