#!/usr/bin/env bash
#Prints "Best School" 10 times and Hi on the 9th line using a while loop 

i=1
while [ $i -le 10 ]
do
    echo "Best School"

    if [ $i = 9 ]
    then
        echo "Hi"
    fi

    i=$((i+1))
done